name: Deploy to neocities

# only run on changes to main. Use main or master depending on whatever your default branch is called.
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build w/ Trunk
    runs-on:
      ubuntu-latest
      # The checkout step copies your repo into the action runner. Important!
    steps:
      - uses: actions/checkout@v4
      # Set up any tools and build steps here
      # This example uses a Node.js toolchain to build a site
      # If you don't need Node.js to build your site, you can omit this.
      # If you have a different build process, replace this with your own build steps
      - name: Install deps and build
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install cargo-binstall
          cargo binstall trunk
          sudo gem uninstall httpclient
          sudo gem install neocities
          trunk build --release

  deploy:
    name: Deploys static site to Neocities
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      # When the dist_dir is ready, deploy it to neocities
      # Here we deploy the folder named `public`
      - name: Deploy to neocities
        # ${{ secrets.NEOCITIES_API_TOKEN }}
        run: |
          echo "wizards-lair\n${{ secrets.NEOCITIES_API_TOKEN }}" | neocities list
